// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwxpWxfBQqqc-HuHhosP_xMI8Of8_K87E',
    appId: '1:382288582106:android:e96a8c6622a6f18e371ce3',
    messagingSenderId: '382288582106',
    projectId: 'teamflow-d217e',
    storageBucket: 'teamflow-d217e.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbcOJiuUmb9ZOKGt1r3usQwORpdRxUtsw',
    appId: '1:382288582106:web:d5f9e0b0cdc78f15371ce3',
    messagingSenderId: '382288582106',
    projectId: 'teamflow-d217e',
    authDomain: 'teamflow-d217e.firebaseapp.com',
    storageBucket: 'teamflow-d217e.firebasestorage.app',
    measurementId: 'G-07SVGKFJBH',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDHUK0ij2AUBUV_nDQw3uFfxX-L4RXuXs',
    appId: '1:382288582106:ios:375541147c620c45371ce3',
    messagingSenderId: '382288582106',
    projectId: 'teamflow-d217e',
    storageBucket: 'teamflow-d217e.firebasestorage.app',
    iosBundleId: 'com.dramirez.teamflow',
  );
}
